brew "jq"
brew "unzip"
brew "mise"
brew "gitui"
brew "ripgrep"
brew "fd"
brew "bat"
brew "fzf"
brew "git-delta"
tap "yqrashawn/goku"
brew "yqrashawn/goku/goku"

cask "kitty"
cask "font-caskaydia-cove-nerd-font"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
