[tools]
"aqua:astral-sh/uv" = "latest"
node = "lts"
python = "3"
usage = "latest"
gitui = "latest"
delta = "latest"
aube = "latest"
"npm:@sap/cds-lsp" = "latest"
"aqua:astral-sh/ruff" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"

[settings]
default_config_filename = ".tool-versions"
asdf_compat = true